// <auto-generated />
using System;
using Gunluk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230104121412_Ilk")]
    partial class Ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazı 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4752),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4742)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazı 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4804),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4804)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazı 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4808),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4807)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazı 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4812),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4811)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazı 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4815),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4814)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazı 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4819),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4818)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazı 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4823),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4822)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazı 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4826),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4826)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazı 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4830),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4829)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazı 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4833),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4832)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazı 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4837),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4836)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazı 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4841),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4840)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazı 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4844),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4843)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazı 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4848),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4847)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazı 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4851),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4850)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazı 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4855),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4854)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazı 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4858),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4857)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazı 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4862),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4861)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazı 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4865),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4865)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazı 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4869),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4868)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazı 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4872),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4872)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazı 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4876),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4875)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazı 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4880),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4879)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazı 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4883),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4883)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazı 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4887),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4886)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazı 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4890),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4890)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazı 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4894),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4893)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazı 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4898),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4897)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazı 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4901),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4900)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazı 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4904),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4904)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazı 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4908),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4907)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazı 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4911),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4911)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazı 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4915),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4914)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazı 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4918),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4918)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazı 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4922),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4921)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazı 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4925),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4924)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazı 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4929),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4928)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazı 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4956),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4955)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazı 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4961),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4960)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazı 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4964),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4963)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazı 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4968),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4967)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazı 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4971),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4970)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazı 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4975),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4974)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazı 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4978),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4978)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazı 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4982),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4981)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazı 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4985),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4984)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazı 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4989),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4988)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazı 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4992),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 12, 277, DateTimeKind.Local).AddTicks(4991)
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş Dünyam"
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.HasOne("Gunluk.Data.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
